name: Node.js CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: running server    
      run: |
        sudo apt-get install libpython3.12-dev
        sudo chmod 777 ./deployAndRun 
        ./deployAndRun 8086
        
    
