

name: secrets fetching from zvAction
on : [push,workflow_dispatch]
jobs: 
  retrive_secrets:
  
    uses: naveennv2k/ZVSecretsLoading/.github/workflows/main.yml@main
    with: 
      secretName: "myPassword"
    secrets: 
      master_password : ${{secrets.MASTER_PASSWORD}}
  job2:
    runs-on: ubuntu-latest
    needs: retrive_secrets
    steps:
     - name: view username
       run: echo ${{steps.zvLoading.outputs.username}}
     - name: view password
       run: echo  password=$(gpg --decrypt --quiet --batch --passphrase "SECRET" --output - <(echo "${steps.zvLoading.outputs.password}}" | base64 --decode))

       
         
    
      
    
              
      

        
  
 
   
  
  
