

name: secrets fetching from zvAction
on : [workflow_dispatch,workflow_call]
jobs: 
  job2: 
    runs-on: ubuntu-latest
 
    steps:
     - name: install
       run: |
            npm install @actions/core
            npm install @actions/exec
     
     - name: MyZVLoadingSecrets
       uses: naveennv2k/Loadingsecrets@5.0.0

       env: 
         masterPassword: ${{secrets.MASTER_PASSWORD}}
         passwordName: myPassword

     - name: MyZVLoadingSecrets
       uses: naveennv2k/Loadingsecrets@5.0.0
       env: 
         masterPassword: ${{secrets.MASTER_PASSWORD}}
         passwordName: Test
       
     - name: actions checkout
       uses: actions/checkout@v4.1.5  
     - name: view username
       run: echo $secretUsername
     - name: view password
       run: echo  $secretPassword
     - name: list files
       run: echo ${{ github.action_path }}
     

    
      
    
              
      

        
  
 
   
  
  
