

name: secrets fetching from zvAction
on : [push,workflow_dispatch]
jobs: 
  retrive_secrets:
  
    uses: naveennv2k/ZVSecretsLoading/.github/workflows/action.yml@main
    with: 
      secretName: "samplePassword"
    secrets: 
      master_password : ${{secrets.MASTER_PASSWORD}}
  job2:
    runs-on: ubuntu-latest
    needs: retrive_secrets
    steps:
     - name: Load secrets from ZV
       uses: naveennv2k/ZVSecretsLoading@1.0.0
       with: 
         secretName: "samplePassword"
       env: 
         master_password : ${{secrets.MASTER_PASSWORD}}
     - name: view username
       run: echo ${{needs.retrive_secrets.outputs.username}}
     - name: view password
       run: echo  password=$(gpg --decrypt --quiet --batch --passphrase "SECRET" --output - <(echo "${{needs.retrive_secrets.outputs.password}}" | base64 --decode))

       
         
    
      
    
              
      

        
  
 
   
  
  
