

name: secrets fetching from zvAction
on : [push,workflow_dispatch]
jobs: 
  retrive_secrets:
  
    uses: naveennv2k/ZVSecretsLoading/.github/workflows/action.yml@main
    with: 
      secretName: "myPassword"
    secrets: 
      master_password : ${{secrets.MASTER_PASSWORD}}
  job2: 
    runs-on: ubuntu-latest
    needs: retrive_secrets
    steps:
     - name: view username
       run: echo ${{needs.retrive_secrets.outputs.username}}
     - name: retSecrets
       run: |
          echo "Secret Output: ${{ toJson(needs.example_job.outputs.password) }}" # Accessing the secret output from the reusable workflow
      
     
     - name: view username
       run: echo ${{needs.retrive_secrets.outputs.Password}}  
       
    
      
    
              
      

        
  
 
   
  
  
