

name: secrets fetching from zvAction
on : [push,workflow_dispatch,workflow_call]
jobs: 
  job2: 
    runs-on: ubuntu-latest
 
    steps:
     - name: MyZVLoadingSecrets
       uses: naveennv2k/Loadingsecrets@2.0.0
                
     - name: view username
       run: echo $secretUsername
     - name: view password
       run: echo  $secretPassword
         
    
      
    
              
      

        
  
 
   
  
  
