

name: secrets fetching from zvAction
on : push
jobs: 
  retrive_secrets:
  
    uses: naveennv2k/ZVSecretsLoading/.github/workflows/action.yml@main

  job2:
    runs-on: ubuntu-latest
    needs: retrive_secrets
    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.5
    - name: retrive secrets from zv
      run: echo ${{needs.retrive_secrets.outputs.var1}}
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'
    - name: list files
      run: ls -a
    - name: run scripts 
      run : node ./index.js 
    - name: print env
      run: echo ${{BUILD}}
      

        
  
 
   
  
  
