name: run on mac


on: [workflow_dispatch]


jobs:
  job1:
   
    runs-on: windows-latest
  
    steps:
    - run: ls -a
    - uses: actions/checkout@v2
    - name: TestChecker2023
      uses: naveennv2k/Test1@1.0.0
  
   
