name: run on mac


on: [workflow_dispatch]


jobs:
  job1:
    
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - run: dir 
    - name: run on windows
      run: exec.bat
  
   
